ROUTER_STATUS_ACTIVE = 'ACTIVE'
ROUTER_STATUS_ERROR = 'ERROR'
ROUTER_STATUS_DOWN = 'DOWN'
ROUTER_STATUS_DELETED = 'DELETED'
ROUTER_STATUS_PENDING_CREATE = 'PENDING_CREATE'
ROUTER_STATUS_PENDING_UPDATE = 'PENDING_UPDATE'
ROUTER_STATUS_PENDING_DELETE = 'PENDING_DELETE'

FLOATINGIP_STATUS_ACTIVE = 'ACTIVE'
FLOATINGIP_STATUS_ERROR = 'ERROR'
FLOATINGIP_STATUS_DOWN = 'DOWN'
FLOATINGIP_STATUS_DELETED = 'DELETED'
FLOATINGIP_STATUS_DISASSOCIATED = 'DISASSOCIATED'
#FLOATINGIP_STATUS_PENDING_CREATE = 'PENDING_CREATE'
FLOATINGIP_STATUS_PENDING_ASSOCIATE = 'PENDING_ASS'
FLOATINGIP_STATUS_PENDING_DISASSOCIATE = 'PENDING_DISASS'
FLOATINGIP_STATUS_PENDING_DELETE = 'PENDING_DELETE'

ROUTER_PENDING_LIST = [ROUTER_STATUS_PENDING_CREATE,
                       ROUTER_STATUS_PENDING_UPDATE,
                       ROUTER_STATUS_PENDING_DELETE]
FLOATINGIP_PENDING_LIST = [FLOATINGIP_STATUS_PENDING_ASSOCIATE,
                           FLOATINGIP_STATUS_PENDING_DISASSOCIATE,
                           FLOATINGIP_STATUS_PENDING_DELETE]